name: manager
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas=2.3.1
  - plotnine=0.15.0
  - ipython=9.4
  - pip=25.1
  - pip:
    - pyfixest==0.30.2
  - jupyter=1.1.1
  - scikit-learn=1.7.1
  - matplotlib=3.10.5
  - wordcloud=1.9.4
  - seaborn=0.13.2
  - numpy=2.3.2
  - polars=1.32.0
  - python=3.12
